[program:myblog-ssr]
process_name=%(program_name)s
command=php /var/www/myblog/artisan inertia:start-ssr
directory=/var/www/myblog
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/myblog/storage/logs/inertia-ssr.log
